import { ProcessorProfile } from '../profile';

export const mipsProfile: ProcessorProfile = {
  name: 'MIPS',
  dataWidth: 32,
  instructionWidth: 32,
  registerCount: 32,
  harvard: true,
  instructionSet: [
    {
      mnemonic: 'ADD',
      opcode: 0x00,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'rd', width: 5 },
        { name: 'shamt', width: 5 },
        { name: 'funct', width: 6 },
      ],
      dispatchField: 'funct',
      dispatchValue: 0x20,
      srcRegFields: ['rs', 'rt'],
      destRegField: 'rd',
      aluOp: { opSel0: 0, opSel1: 0 },
      aluSecondOperand: 'register',
      writesRegFrom: 'alu',
    },
    {
      mnemonic: 'SUB',
      opcode: 0x00,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'rd', width: 5 },
        { name: 'shamt', width: 5 },
        { name: 'funct', width: 6 },
      ],
      dispatchField: 'funct',
      dispatchValue: 0x22,
      srcRegFields: ['rs', 'rt'],
      destRegField: 'rd',
      aluOp: { opSel0: 1, opSel1: 0 },
      aluSecondOperand: 'register',
      writesRegFrom: 'alu',
    },
    {
      mnemonic: 'AND',
      opcode: 0x00,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'rd', width: 5 },
        { name: 'shamt', width: 5 },
        { name: 'funct', width: 6 },
      ],
      dispatchField: 'funct',
      dispatchValue: 0x24,
      srcRegFields: ['rs', 'rt'],
      destRegField: 'rd',
      aluOp: { opSel0: 0, opSel1: 1 },
      aluSecondOperand: 'register',
      writesRegFrom: 'alu',
    },
    {
      mnemonic: 'OR',
      opcode: 0x00,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'rd', width: 5 },
        { name: 'shamt', width: 5 },
        { name: 'funct', width: 6 },
      ],
      dispatchField: 'funct',
      dispatchValue: 0x25,
      srcRegFields: ['rs', 'rt'],
      destRegField: 'rd',
      aluOp: { opSel0: 1, opSel1: 1 },
      aluSecondOperand: 'register',
      writesRegFrom: 'alu',
    },
    {
      mnemonic: 'SLT',
      opcode: 0x00,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'rd', width: 5 },
        { name: 'shamt', width: 5 },
        { name: 'funct', width: 6 },
      ],
      dispatchField: 'funct',
      dispatchValue: 0x2A,
      srcRegFields: ['rs', 'rt'],
      destRegField: 'rd',
      aluOp: { opSel0: 1, opSel1: 0 },
      aluSecondOperand: 'register',
      writesRegFrom: 'aluSignBit',
    },
    {
      mnemonic: 'ADDI',
      opcode: 0x08,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'immediate', width: 16 },
      ],
      srcRegFields: ['rs'],
      destRegField: 'rt',
      aluOp: { opSel0: 0, opSel1: 0 },
      aluSecondOperand: 'immediate',
      aluImmediateField: 'immediate',
      writesRegFrom: 'alu',
    },
    {
      mnemonic: 'LW',
      opcode: 0x23,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'immediate', width: 16 },
      ],
      srcRegFields: ['rs'],
      destRegField: 'rt',
      aluOp: { opSel0: 0, opSel1: 0 },
      aluSecondOperand: 'immediate',
      aluImmediateField: 'immediate',
      memOp: 'read',
      memAddressField: 'immediate',
      writesRegFrom: 'memory',
    },
    {
      mnemonic: 'SW',
      opcode: 0x2B,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'immediate', width: 16 },
      ],
      srcRegFields: ['rs', 'rt'],
      aluOp: { opSel0: 0, opSel1: 0 },
      aluSecondOperand: 'immediate',
      aluImmediateField: 'immediate',
      memOp: 'write',
      memAddressField: 'immediate',
    },
    {
      mnemonic: 'BEQ',
      opcode: 0x04,
      opcodeWidth: 6,
      fields: [
        { name: 'rs', width: 5 },
        { name: 'rt', width: 5 },
        { name: 'immediate', width: 16 },
      ],
      srcRegFields: ['rs', 'rt'],
      controlFlow: 'branch',
      branchTargetKind: 'pcRelative',
      branchTargetField: 'immediate',
      aluOp: { opSel0: 1, opSel1: 0 },
      aluSecondOperand: 'register',
    },
    {
      mnemonic: 'J',
      opcode: 0x02,
      opcodeWidth: 6,
      fields: [{ name: 'address', width: 26 }],
      controlFlow: 'jump',
      branchTargetKind: 'absolute',
      branchTargetField: 'address',
    },
    {
      mnemonic: 'HALT',
      opcode: 0x3f,
      opcodeWidth: 6,
      fields: [],
      controlFlow: 'halt',
      // simulator-only HALT instruction; real MIPS uses syscall-based termination.
    },
  ],
};
